### ISSUE TITLE
Code introduction

### ISSUE THREAD

**Issue by cajoek** [CurriculumAssociates/canvas-latex#20]
@ry-randall @mattbargar-cainc Sorry for nagging I just find this repo so useful.
I posted this issue before #12 
If time is the problem maybe you could introduce me to the code and point to where the problem could be so I could fix it and some other problems i found?

Br

**Comment by ry-randall** [comment]
I'm happy you are finding this repo useful. I'll look at the issue this weekend for #12 

With regards to introducing you to the code, I'll try and find some time to do a writeup then as well. Unfortunately with the combination of LaTeX and it being on the canvas, it's not the easiest to get ramped up on. 

Can I ask what sort of projects you're using the repo for? Perhaps I'll carve out more time to push the features further.

**Comment by cajoek** [comment]
Thanks, that would be great!
Sure, it is quite a big project where I'm building an educational platform for students. Instead of just text, the material is presented in a highly visual and interactive way. Some equations are animated and students can drag and drop parts of equations.

**Comment by ry-randall** [comment]
Sounds interesting. I'm assuming the `\class` feature will be helpful for breaking out individual parts of the equations for you. Are you using createjs or pixi?

**Comment by ry-randall** [comment]
Okay, so here's an introduction of the repo:

1. We use KaTeX for parsing the TeX and creating a parse tree. That parse tree then gets converted into "virtual dom nodes". These dom nodes aren't as heavyweight as real dom nodes, but they still mimic a close representation of the dom. This is all done via KaTeX, and you'll find it here: https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/VirtualNodeBuilder.js#L51 . I would recommend console logging this out to get familiar with some of the structure.

2. Like any dom nodes, these contain class/style data. We take that class/style data and convert it to it's canvas representation. Thankfully, I've already made most of these canvas conversion helpers, and you'd likely be re-using the existing ones I made. You'll find the class mapping here: https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/classStateMapping.js and the style mapping here: https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/styleStateMapping.js

3. Those class/style primarily all use the underlying "state" to keep track of the current state when navigating through the virtual dom tree. You'll see that used here: https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/RenderingState.js . The tricky part is determining how to best map dom manipulations to canvas, but most of those helper methods should do the heavy lifting for you. 

4. After all the class/style data has been properly calculated, you'll build the "virtual canvas nodes" with the current state object. These nodes can be text, boxes, svg's, lines, etc. Here's an example of a text node being created: https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/VirtualNodeBuilder.js#L169-L180

5. Eventually, the full tree will be traversed and you'll end up with a big "virtual canvas tree" which contains canvas friendly rendering data. It'll look something like https://github.com/CurriculumAssociates/canvas-latex/blob/master/test/unit/tests/__snapshots__/NodeBuilder.test.js.snap#L15-L160

6. You can then convert that canvas friendly data into any rendering format you choose (primarily good for canvas). 

Unfortunately, this is a rather unique solution since it relies on the virtual dom nodes to be converted into canvas friendly rendering data. Ideally we'd have a better intermediate representation that could go from IR -> html, IR -> canvas, etc. That's something I chatted with the `KaTeX` team about a while ago, but I think someone would need to take the reins on it to really push it: https://github.com/KaTeX/KaTeX/issues/376

As I am learning, I no longer have time to maintain this repo so it's unfair for me to pretend like I do. I think the folks at Curriculum Associates will be able to provide a lot more help than me.

I hope this helps!

cc @LinGrin @rfandl-cainc @mattbargar-cainc

**Comment by cajoek** [comment]
Thanks @ry-randall @LinGrin! This was quite complicated.
I'm trying to fix `\underbrace` and `\overbrace` which only adds an extra horizontal line which shouldn't be there.
But I don't understand where this problem originates, do you?

Thanks!
(I understand if you don't have time)

**Comment by LinGrin** [comment]
@cajoek Thanks for bringing this to our attention; we’ll take a look at this! If you wouldn't mind though, could you open a separate issue for addressing this?
Initial thoughts are that it stems from the KaTeX portion of this repo: katex.min.js.
We are using an old fork of KaTeX and and are working on updating the way we leverage that as a dependency as a longer term goal so it will be easier to understand and update in the future.

**Comment by cajoek** [comment]
Of course!
