### ISSUE TITLE
status of canvas-latex?

### ISSUE THREAD

**Issue by kortenkamp** [CurriculumAssociates/canvas-latex#71]
Can somebody comment on the current status of canvas-latex? We are using an ancient version of [KaTeX](https://github.com/KaTeX/KaTeX) in our project [CindyJS](https://github.com/CindyJS/CindyJS) that relies on a [branch that has never been pulled](https://github.com/KaTeX/KaTeX/pull/251) that can render to a canvas. We would like to move on to a newer KaTeX version, and I wonder whether it is worthwhile using canvas-latex or whether we should come up with a different approach. See [our own issue here](https://github.com/CindyJS/CindyJS/issues/829).

Thanks for any insight, Ulli

**Comment by ryan-managai** [comment]
Sorry, I haven't kept up-to-date with the comments from: https://github.com/KaTeX/KaTeX/pull/251. Probably because I haven't used that git profile in a while. 

It's been a while, so I'll try my best to remember what I can. 

This repo is based on a specific version of KaTeX (essentially forked and frozen) and it uses their "buildTree" to translate into "Virtual Canvas Nodes" which are just super light-weight models that the canvas can interpret: https://github.com/CurriculumAssociates/canvas-latex/tree/main/src/common/virtualCanvasNodes

You can see where it traverses the tree here: https://github.com/CurriculumAssociates/canvas-latex/blob/main/src/common/VirtualNodeBuilder.js#L46-L58. This is useful if you want to build your own canvas-based renderer implementation (i.e. not `createjs` or `pixijs`). You'll get back a bunch of those virtual canvas nodes which should easily translate for canvas based rendering library.

If you want to do interactivity with subsets of the equations, etc. you can use `\class{...}{...}` to separate out your various display objects within a element.

> Can somebody comment on the current status of canvas-latex?

Unfortunately I don't have the time to maintain this anymore. However, I'd recommend seeing if this repo already solves your needs.

If not, then your best bet may be to work w/ integrating it into the KaTeX project. Really, it needs a model that easily can translate to any rendering format, not just HTML. 

That would be a more significant undertaking. If you do choose to go down that route, let me know, and I'd be happy to help contribute when I can.
